import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div className="bg-hero-bg bg-cover h-screen w-screen flex flex-col items-center">
      <Head>
        <title>Sri Laxmi Narayana Jewellers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center hero-txt font-bold text-5xl p-10 pt-20 shadow-cyan-500 drop-shadow-md">
        Your Wedding, Your Style
      </h1>
      <h1 className="text-center xl:px-96 text-xl lg:px-72 md:px-40 px-10 text-neutral-800">
        Antique cream lace, pale pink rose petals, the golden light of a lit
        candle. Celebrations of traditions passed down through generations.
        These ideals are the basis of human life.
      </h1>
      <Link href="/products" passHref>
        <a>
          <button className="mt-5 bg-white p-3 hero-txt-2 rounded-md hover:text-cyan-600 hover:shadow-xl shadow-neutral-500">
            VIEW ALL PRODUCTS
          </button>
        </a>
      </Link>
    </div>
  );
}
